version: "4"
services:
  vue_dev:
    build:
      context: ../frontend/
      dockerfile: Dockerfile 
    container_name: login-vue
    volumes:
      - ../frontend/src:/app
    working_dir: /app
    command: ["yarn", "serve", "--port", "8081"]
    ports:
      - "5123:8081" 
    stdin_open: true
    tty: true

  nginx_server:
    image: nginx:latest
    container_name: login-nginx-server
    depends_on:
      - vue_dev
    volumes:
      - ../frontend/src/dist:/usr/share/nginx/html
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf 
      - ../nginx/ssl:/etc/nginx/ssl
    ports:
    - "8081:80"
    - "8443:443"
  python-service:
    image: python:3.9
    container_name: python-db-query
    volumes:
      - ../backend/app:/app
    working_dir: /app
    command: |
      bash -c "pip install flask psycopg2 flask-bcrypt flask_cors pytest && python app.py"
    depends_on:
      - pgsql
    ports:
      - "5002:5000"

  pgsql:
    image: postgres
    container_name: pgsql_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ../pg_data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"

volumes:
  pg_data:
