version: "4"
services:
  vue_dev:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: login-vue
    volumes:
      - ../frontend/src:/app
      - /app/node_modules
    working_dir: /app
    ports:
    - "5123:8081"
    command: ["yarn", "serve", "--port", "8081"]
    stdin_open: true
    tty: true
    networks:
      - shared_net

  nginx_server:
    image: nginx:latest
    container_name: login-nginx-server
    depends_on:
      - vue_dev
      - python-service
      - backup
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../../photo_syncer/src/face_image:/usr/share/nginx/html/images
      - ../../photo_syncer/src/downloaded_albums:/usr/share/nginx/html/downloaded_albums
    ports:
      - "8081:80"
      - "8443:443"
    networks:
      - shared_net
  python-service:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: python-db-query
    volumes:
      - ../backend/app:/app
    working_dir: /app
    command: ["python", "app.py"]
    depends_on:
      - pgsql
    networks:
      - shared_net
  backup:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: backup
    volumes:
      - ../backend/app:/app
    working_dir: /app
    command: ["python", "app.py"]
    depends_on:
      - pgsql
    networks:
      - shared_net
  mail-service:
    build:
      context: ../backend/
      dockerfile: mail-server/Dockerfile
    container_name: python-mail-server
    volumes:
      - ../backend/mail-server:/app
    working_dir: /app
    command: ["python", "mail_server.py"]
    networks:
      - shared_net
  redis:
    image: redis:5.0.5-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - shared_net
  pgsql:
    image: postgres
    container_name: pgsql_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ../pg_data:/var/lib/postgresql/data
    networks:
      - shared_net
volumes:
  pg_data:

networks:
  shared_net:
    external: true
